name: Static Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps: 
      - name: Install Python
        uses: actions/setup-python@v5
        with:
            cache: 'pip'
      - name: Install Bandit
        run: |
          pip install bandit
      - name: Run Bandit
        run: |
          bandit -r . -ll -ii -f html -o static-analysis-report.html

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-report
          path: static-analysis-report.html